app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod-min-256-bits-long-please-replace}

ordered:
  gateway:
    security:
      jwt-secret: ${JWT_SECRET:change-me-in-prod-min-256-bits-long-please-replace}
